.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH npltz 1 "June 21, 2026" npltz npltz
.SH NAME
npltz \- Nepali calendar and date converter for the terminal
.SH SYNOPSIS
\fBnpltz\fR [\fB\-v\fR|\fB\-\-version\fR] [\fB\-\-set\-theme\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
A terminal\-based Nepali calendar (Bikram Sambat) viewer with an interactive TUI and CLI conversion tools.
.PP
npltz displays Nepali months with English dates alongside, supports AD to BS conversion, and offers simplicity.
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information
.TP
\fB\-\-set\-theme\fR \fI<SET_THEME>\fR
Set default theme (catppuccin\-mocha, dracula, gruvbox, nord, rose\-pine, or default to reset)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH SUBCOMMANDS
.TP
\fBshow\fR
Show today\*(Aqs Nepali and English date
.TP
\fBconvert\fR
Convert an AD date (YYYY\-MM\-DD) to Bikram Sambat
.TP
\fBconvert-bs\fR
Convert a Bikram Sambat date (YYYY\-MM\-DD) to AD
.TP
\fBcompletions\fR
Generate shell completions (bash, zsh, fish)
.TP
\fBhelp\fR
Print this message or the help of the given subcommand(s)
.SH DOCUMENTATION
Documentation and source code available at:
.br
https://github.com/harilvfs/npltz

.SH AUTHOR
Aayush Chalise <me@aayush.xyz>

.SH REPORTING BUGS
If you encounter bugs or issues, please report them at:
.br
https://github.com/harilvfs/npltz/issues

