[licenses]
version = 2
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSL-1.0",
  "MPL-2.0",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]

[licenses.private]
ignore = false

[advisories]
yanked = "deny"
ignore = []
version = 2

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
